# Basics [TensorFlow]
---
- Author: Diego Inácio
- GitHub: [github.com/diegoinacio](https://github.com/diegoinacio)
- Notebook: [basics_TensorFlow.ipynb](https://github.com/diegoinacio/machine-learning-notebooks/blob/master/Deep-Learning-Models/basics_TensorFlow.ipynb)
---
Basic functions and operations using TensorFlow library.

In [1]:
import numpy as np

## Instalation
---
``` python
>>> conda install -c conda-forge tensorflow
```
or
``` python
>>> pip install tensorflow
```

In [2]:
import tensorflow as tf

In [3]:
# un-initialized tensor
a = tf.placeholder(tf.float32, shape=(3, 4), name='a')
# initialized tensor
b = tf.constant(np.arange(12).reshape(3, 4), name='b')

print(a, a.shape, a.dtype)
print(b, b.shape, b.dtype)

Tensor("a:0", shape=(3, 4), dtype=float32) (3, 4) <dtype: 'float32'>
Tensor("b:0", shape=(3, 4), dtype=int32) (3, 4) <dtype: 'int32'>


## Sessions Objects and Output
---

In [4]:
a = tf.constant(np.arange(4), name='a')
b = tf.constant(np.arange(4)*10, name='b')
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(4,), dtype=int32)


In [5]:
# Iteractive session
sess = tf.InteractiveSession()
out = c.eval()
sess.close()

print(out)

[ 0 11 22 33]


In [6]:
# Non-Iteractive session
sess = tf.Session()
out = c.eval(session=sess)
sess.close()

print(out)

[ 0 11 22 33]


In [7]:
# Non-Iteractive session using context manager
with tf.Session() as sess:
    out1 = sess.run(c)
    out2 = c.eval()

print(out1)
print(out2)

[ 0 11 22 33]
[ 0 11 22 33]


### Un-initialized tensor and feed dictionary

In [8]:
a = tf.placeholder(tf.int32, name='a')
b = tf.placeholder(tf.int32, name='b')
c = tf.add(a, b)

with tf.Session() as sess:
    out = sess.run(c, feed_dict={a: 3, b: 4})

print(out)

7


## Basic Operations
---

In [9]:
s = tf.constant(3)                           # scalar
v = tf.constant(np.arange(5))                # vactor n=5
m = tf.constant(np.arange(20).reshape(4, 5)) # matrix 4 x 5

In [10]:
# print S
with tf.Session() as sess:
    print('    S:', sess.run(s))

# V x S product
vs = tf.multiply(v, s) # could be v*s as well
with tf.Session() as sess:
    print('V x S:', sess.run(vs))

# M x S product
ms = tf.multiply(m, s) # could be m*s as well
with tf.Session() as sess:
    print('M x S:\n', sess.run(ms))

    S: 3
V x S: [ 0  3  6  9 12]
M x S:
 [[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]
 [45 48 51 54 57]]


In [11]:
# print V
with tf.Session() as sess:
    print('    V:', sess.run(v))

# V x V > dot product
vv = tf.tensordot(v, v, axes=1)
with tf.Session() as sess:
    print('V x V:', sess.run(vv))

# M x V product
mv = tf.tensordot(m, v, axes=1)
with tf.Session() as sess:
    print('M x V:', sess.run(mv))

    V: [0 1 2 3 4]
V x V: 30
M x V: [ 30  80 130 180]


In [12]:
# print M
with tf.Session() as sess:
    print('     M:\n', sess.run(m))

# M x M product
m1 = tf.constant(np.arange(15).reshape(5, 3)) # the M1's dimensions are 5 x 3
mm = tf.matmul(m, m1)                         # the result dimensions must be 4 x 3

with tf.Session() as sess:
    print('\nM x M1:\n', sess.run(mm))

     M:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

M x M1:
 [[ 90 100 110]
 [240 275 310]
 [390 450 510]
 [540 625 710]]
