# Basics [PyTorch]
---
- Author: Diego Inácio
- GitHub: [github.com/diegoinacio](https://github.com/diegoinacio)
- Notebook: [MCLR_PyTorch.ipynb](https://github.com/diegoinacio/machine-learning-notebooks/blob/master/Deep-Learning-Models/MCLR_PyTorch.ipynb)

In [1]:
import numpy as np

## Instalation
---
``` python
>>> conda install -c pytorch pytorch
```
or
``` python
>>> pip install pytorch
```

In [2]:
import torch

In [3]:
# un-initialized tensor
a = torch.Tensor(3, 4)
# initialized tensor
b = torch.Tensor(np.arange(12).reshape(3, 4))

print(a, a.shape, a.dtype)
print(b, b.shape, b.dtype)

tensor([[1.3733e-14, 6.4076e+07, 2.0706e-19, 7.3909e+22],
        [2.4176e-12, 1.1625e+33, 8.9605e-01, 1.1632e+33],
        [5.6003e-02, 7.0374e+22, 5.7453e-44, 0.0000e+00]]) torch.Size([3, 4]) torch.float32
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) torch.Size([3, 4]) torch.float32


## Sessions Objects and Output
---

In [4]:
a = torch.Tensor(np.arange(4))
b = torch.Tensor(np.arange(4)*10)
c = torch.add(a, b)
print(c)

tensor([ 0., 11., 22., 33.])


In [5]:
out = c.numpy()

print(out)

[ 0. 11. 22. 33.]


In [6]:
out = torch.Tensor(a.shape)
torch.add(a, b, out=out)
out = out.numpy()

print(out)

[ 0. 11. 22. 33.]


## Basic Operations
---

In [7]:
s = 3                            # scalar
v = torch.Tensor(np.arange(5))                # vactor n=5
m = torch.Tensor(np.arange(20).reshape(4, 5)) # matrix 4 x 5

In [8]:
# print S
print('    S:', s)

# V x S product
vs = v*s
print('V x S:', vs.numpy())

# M x S product
ms = m*s
print('M x S:\n', ms.numpy())

    S: 3
V x S: [ 0.  3.  6.  9. 12.]
M x S:
 [[ 0.  3.  6.  9. 12.]
 [15. 18. 21. 24. 27.]
 [30. 33. 36. 39. 42.]
 [45. 48. 51. 54. 57.]]


In [9]:
# print V
print('    V:', v.numpy())

# V x V > dot product
vv = torch.dot(v, v)
print('V x V:', vv.numpy())

# M x V product
mv = torch.mv(m, v)
print('M x V:', mv.numpy())

    V: [0. 1. 2. 3. 4.]
V x V: 30.0
M x V: [ 30.  80. 130. 180.]


In [10]:
# print M
print('     M:\n', m.numpy())

# M x M product
m1 = torch.Tensor(np.arange(15).reshape(5, 3)) # the M1's dimensions are 5 x 3
mm = torch.mm(m, m1)                           # the result dimensions must be 4 x 3

print('\nM x M1:\n', mm.numpy())

     M:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]

M x M1:
 [[ 90. 100. 110.]
 [240. 275. 310.]
 [390. 450. 510.]
 [540. 625. 710.]]
